cloud:
  aws:
    credentials:
      access-key: ASIA2M5Z45KPZAK45DGV
      secret-key: dPfihZIWOJMjtpBXzA+YMOeHSHXKbHEAB4u3EYDw
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: vgstorage


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090